export const BOOK_REGISTER_REQUEST = 'BOOK_REGISTER_REQUEST'
export const BOOK_REGISTER_SUCCESS = 'BOOK_REGISTER_SUCCESS'
export const BOOK_REGISTER_FAIL = 'BOOK_REGISTER_FAIL'

export const AUTHOR_BOOK_DETAILS_REQUEST = 'AUTHOR_BOOK_DETAILS_REQUEST'
export const AUTHOR_BOOK_DETAILS_SUCCESS = 'AUTHOR_BOOK_DETAILS_SUCCESS'
export const AUTHOR_BOOK_DETAILS_FAIL = 'AUTHOR_BOOK_DETAILS_FAIL'