export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const ADD_TESTIMONIAL_REQUEST = 'ADD_TESTIMONIAL_REQUEST'
export const ADD_TESTIMONIAL_SUCCESS = 'ADD_TESTIMONIAL_SUCCESS'
export const ADD_TESTIMONIAL_FAIL = 'ADD_TESTIMONIAL_FAIL'

export const GET_TESTIMONIAL_BY_EMAIL_REQUEST = 'GET_TESTIMONIAL_BY_EMAIL_REQUEST'
export const GET_TESTIMONIAL_BY_EMAIL_SUCCESS = 'GET_TESTIMONIAL_BY_EMAIL_SUCCESS'
export const GET_TESTIMONIAL_BY_EMAIL_FAIL = 'GET_TESTIMONIAL_BY_EMAIL_FAIL'


export const GET_TESTIMONIAL_REQUEST = 'GET_TESTIMONIAL_REQUEST'
export const GET_TESTIMONIAL_SUCCESS = 'GET_TESTIMONIAL_SUCCESS'
export const GET_TESTIMONIAL_FAIL = 'GET_TESTIMONIAL_FAIL'


export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'